
SELECT 
    UPRN, 
    SOURCE,
    CHANGE_TYPE,
    LISTING_ID,
    LISTING_ID_SEQ, 
    FIRST_LISTING_DATE,
    LAST_UPDATE_DATE,    
    DENSE_RANK() OVER (PARTITION BY UPRN ORDER BY FIRST_LISTING_DATE) AS EPISODE
    --SUM(CASE WHEN CHANGE_TYPE = 'addition' THEN 1 ELSE 0 END) OVER (PARTITION BY UPRN  ORDER BY FIRST_LISTING_DATE) AS EPISODE   -- 
FROM SILVER_DEV.FORECASTING.FRC_LISTINGS
--WHERE "UPRN" = 100000000771
WHERE "UPRN" = 100110626866
--WHERE "UPRN" = '10000446605'
--WHERE "UPRN" = 6057668
--ORDER BY LISTING_ID_SEQ, LAST_UPDATE_DATE
ORDER BY EPISODE, LISTING_ID_SEQ,LAST_UPDATE_DATE
